import mongoose from "mongoose";
import { ID_SUFFIX, REF_GOLDENGATE, TYPE_MENU } from "../constants";

const generateId = (index: number) => new mongoose.Types.ObjectId(`${REF_GOLDENGATE}${TYPE_MENU}${ID_SUFFIX}${index.toString().padStart(6, "0")}`);

export const menus = [
	{
		_id: generateId(1),
		restaurantID: "goldengate",
		name: "Special Kitfo (ስፔሻል ክትፎ)",
		description: "Minced lean beef seasoned with mitmita and niter kibbeh, served with ayib and gomen.",
		category: "Ethiopian Specials",
		price: 650,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/kitfo.png",
		hidden: false,
	},
	{
		_id: generateId(2),
		restaurantID: "goldengate",
		name: "Doro Wot (ዶሮ ወጥ)",
		description: "Spicy chicken stew slow-cooked with berbere, onions, and hard-boiled egg.",
		category: "Ethiopian Specials",
		price: 700,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/doro_wot.png",
		hidden: false,
	},
	{
		_id: generateId(3),
		restaurantID: "goldengate",
		name: "Shiro Tegamino (ሽሮ ተጋቢኖ)",
		description: "Rich and flavorful chickpea stew served bubbling hot in a clay pot.",
		category: "Vegetarian",
		price: 350,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/shiro.png",
		hidden: false,
	},
	{
		_id: generateId(4),
		restaurantID: "goldengate",
		name: "Tibs (ጥብስ)",
		description: "Sizzling cubed meat (beef or lamb) sautéed with onions, rosemary, and jalapeños.",
		category: "Ethiopian Specials",
		price: 550,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/tibs.png",
		hidden: false,
	},
	{
		_id: generateId(5),
		restaurantID: "goldengate",
		name: "Beyaynetu (በያይነቱ)",
		description: "Vegetarian fasting platter offering an assortment of colorful stews and vegetables.",
		category: "Vegetarian",
		price: 450,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/beyaynetu.png",
		hidden: false,
	},
	{
		_id: generateId(6),
		restaurantID: "goldengate",
		name: "Ethiopian Coffee (ቡና)",
		description: "Traditional freshly roasted and brewed Ethiopian coffee.",
		category: "Beverages",
		price: 50,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/coffee.png",
		hidden: false,
	},
	{
		_id: generateId(7),
		restaurantID: "goldengate",
		name: "Tej (ጠጅ)",
		description: "Traditional honey wine, sweet and potent.",
		category: "Beverages",
		price: 150,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/tej.png",
		hidden: false,
	},
	{
		_id: generateId(8),
		restaurantID: "goldengate",
		name: "Gomen Be Siga (ጎመን በስጋ)",
		description: "Tender beef chunks sautéed with fresh collard greens, onions, and garlic.",
		category: "Ethiopian Specials",
		price: 580,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/gomen_be_siga.png",
		hidden: false,
	},
	{
		_id: generateId(9),
		restaurantID: "goldengate",
		name: "Key Wot (ቀይ ወጥ)",
		description: "Spicy and flavorful beef stew slow-cooked with berbere and traditional spices.",
		category: "Ethiopian Specials",
		price: 620,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/key_wot.png",
		hidden: false,
	},
	{
		_id: generateId(10),
		restaurantID: "goldengate",
		name: "Alicha Wot (አሊጫ ወጥ)",
		description: "Mild beef stew cooked with turmeric, onions, and ginger for a delicate flavor.",
		category: "Ethiopian Specials",
		price: 600,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/alicha_wot.png",
		hidden: false,
	},
	{
		_id: generateId(11),
		restaurantID: "goldengate",
		name: "Shiro Fitfit (ሽሮ ፍትፍት)",
		description: "Broken pieces of injera mixed with a chilled shiro sauce, onions, and green chilies.",
		category: "Vegetarian",
		price: 320,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/shiro_fitfit.png",
		hidden: false,
	},
	{
		_id: generateId(12),
		restaurantID: "goldengate",
		name: "Check Tibs (ቸክ ጥብስ)",
		description: "Small cubes of beef pan-fried with onions, green pepper, and rosemary.",
		category: "Ethiopian Specials",
		price: 590,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/check_tibs.png",
		hidden: false,
	},
	{
		_id: generateId(13),
		restaurantID: "goldengate",
		name: "Zilzil Tibs (ዝልዝል ጥብስ)",
		description: "Long strips of beef pan-fried until tender-crisp, served with awaze sauce.",
		category: "Ethiopian Specials",
		price: 640,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/zilzil_tibs.png",
		hidden: false,
	},
	{
		_id: generateId(14),
		restaurantID: "goldengate",
		name: "Miser Wot (ምስር ወጥ)",
		description: "Red split lentils slow-cooked in a spicy berbere sauce.",
		category: "Vegetarian",
		price: 380,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/miser_wot.png",
		hidden: false,
	},
	{
		_id: generateId(15),
		restaurantID: "goldengate",
		name: "Quanta Fitfit (ቋንጣ ፍትፍት)",
		description: "Dried beef jerky pieces sautéed in spicy sauce and mixed with pieces of injera.",
		category: "Ethiopian Specials",
		price: 680,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/quanta_fitfit.png",
		hidden: false,
	},
	{
		_id: generateId(16),
		restaurantID: "goldengate",
		name: "Chechebsa (ጨጨብሳ)",
		description: "Shredded flatbread braised with niter kibbeh and berbere, served with honey and yogurt.",
		category: "Ethiopian Specials",
		price: 420,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/chechebsa.png",
		hidden: false,
	},
	{
		_id: generateId(17),
		restaurantID: "goldengate",
		name: "Large Beyaynetu (ትልቅ በያይነቱ)",
		description: "A grand assortment of 12+ traditional vegetarian stews, salads, and vegetables.",
		category: "Vegetarian",
		price: 750,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/big_beyaynetu.png",
		hidden: false,
	},
	{
		_id: generateId(18),
		restaurantID: "goldengate",
		name: "Grilled Ribeye Steak",
		description: "Prime beef ribeye grilled to your liking, served with mashed potatoes and seasonal vegetables.",
		category: "Main Course",
		price: 1250,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/ribeye_steak.png",
		hidden: false,
	},
	{
		_id: generateId(19),
		restaurantID: "goldengate",
		name: "Classic Cheeseburger",
		description: "Juicy beef patty with cheddar cheese, lettuce, tomato, and onions on a brioche bun.",
		category: "Burgers & Sandwiches",
		price: 650,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/cheeseburger.png",
		hidden: false,
	},
	{
		_id: generateId(20),
		restaurantID: "goldengate",
		name: "Chicken Alfredo",
		description: "Fettuccine pasta tossed in a rich and creamy parmesan sauce with grilled chicken breast.",
		category: "Pasta & Pizza",
		price: 850,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/chicken_alfredo.png",
		hidden: false,
	},
	{
		_id: generateId(21),
		restaurantID: "goldengate",
		name: "Margherita Pizza",
		description: "Traditional stone-baked pizza with fresh mozzarella, tomato sauce, and basil leaves.",
		category: "Pasta & Pizza",
		price: 720,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/margherita_pizza.png",
		hidden: false,
	},
	{
		_id: generateId(22),
		restaurantID: "goldengate",
		name: "Beef Lasagna",
		description: "Layers of pasta with rich meat sauce, béchamel, and melted mozzarella cheese.",
		category: "Pasta & Pizza",
		price: 880,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/lasagna.png",
		hidden: false,
	},
	{
		_id: generateId(23),
		restaurantID: "goldengate",
		name: "Caesar Salad with Chicken",
		description: "Crisp romaine lettuce, croutons, and parmesan cheese tossed in Caesar dressing with grilled chicken.",
		category: "Starters & Sides",
		price: 550,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/caesar_salad.png",
		hidden: false,
	},
	{
		_id: generateId(24),
		restaurantID: "goldengate",
		name: "Fish and Chips",
		description: "Golden-fried battered fish served with chunky fries and tartar sauce.",
		category: "Main Course",
		price: 780,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/fish_chips.png",
		hidden: false,
	},
	{
		_id: generateId(25),
		restaurantID: "goldengate",
		name: "Club Sandwich",
		description: "Triple-decker sandwich with chicken, bacon, lettuce, tomato, and mayo, served with fries.",
		category: "Burgers & Sandwiches",
		price: 680,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/club_sandwich.png",
		hidden: false,
	},
	{
		_id: generateId(26),
		restaurantID: "goldengate",
		name: "Pepperoni Pizza",
		description: "Stone-baked pizza topped with spicy pepperoni and generous mozzarella cheese.",
		category: "Pasta & Pizza",
		price: 820,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/pepperoni_pizza.png",
		hidden: false,
	},
	{
		_id: generateId(27),
		restaurantID: "goldengate",
		name: "BBQ Chicken Wings",
		description: "12 pieces of crispy wings tossed in a smoky and sweet BBQ sauce.",
		category: "Starters & Sides",
		price: 850,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/bbq_wings.png",
		hidden: false,
	},
	{
		_id: generateId(28),
		restaurantID: "goldengate",
		name: "Mushroom Risotto",
		description: "Creamy Arborio rice cooked with wild mushrooms, garlic, and truffle oil essence.",
		category: "Main Course",
		price: 820,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/mushroom_risotto.png",
		hidden: false,
	},
	{
		_id: generateId(29),
		restaurantID: "goldengate",
		name: "New York Cheesecake",
		description: "Rich and creamy classic cheesecake served with a berry compote.",
		category: "Desserts",
		price: 450,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/cheesecake.png",
		hidden: false,
	},
	{
		_id: generateId(30),
		restaurantID: "goldengate",
		name: "Chocolate Lava Cake",
		description: "Warm chocolate cake with a molten center, served with vanilla ice cream.",
		category: "Desserts",
		price: 480,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/lava_cake.png",
		hidden: false,
	},
	{
		_id: generateId(31),
		restaurantID: "goldengate",
		name: "Large French Fries",
		description: "A large portion of golden, crispy salted fries.",
		category: "Starters & Sides",
		price: 250,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/fries.png",
		hidden: false,
	},
	{
		_id: generateId(32),
		restaurantID: "goldengate",
		name: "Crispy Onion Rings",
		description: "Beer-battered onion rings fried to a perfect golden brown.",
		category: "Starters & Sides",
		price: 320,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/onion_rings.png",
		hidden: false,
	},
	{
		_id: generateId(33),
		restaurantID: "goldengate",
		name: "Double Bacon Burger",
		description: "Two beef patties with crispy bacon strips and melted American cheese.",
		category: "Burgers & Sandwiches",
		price: 890,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/bacon_burger.png",
		hidden: false,
	},
	{
		_id: generateId(34),
		restaurantID: "goldengate",
		name: "Eggs Benedict",
		description: "Poached eggs and Canadian bacon on English muffins, topped with hollandaise sauce.",
		category: "Main Course",
		price: 580,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/eggs_benedict.png",
		hidden: false,
	},
	{
		_id: generateId(35),
		restaurantID: "goldengate",
		name: "Blueberry Pancakes",
		description: "Fluffy pancake stack stuffed with fresh blueberries and served with maple syrup.",
		category: "Desserts",
		price: 420,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/pancakes.png",
		hidden: false,
	},
	{
		_id: generateId(36),
		restaurantID: "goldengate",
		name: "Spaghetti Carbonara",
		description: "Classic Italian pasta with eggs, cheese, pancetta, and black pepper.",
		category: "Pasta & Pizza",
		price: 780,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/western_food/carbonara.png",
		hidden: false,
	},
	{
		_id: generateId(37),
		restaurantID: "goldengate",
		name: "Vegetable Stir-Fry",
		description: "Fresh garden vegetables sautéed in a savory soy and ginger sauce, served with rice.",
		category: "Vegetarian",
		price: 520,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/western_food/stir_fry.png",
		hidden: false,
	},
];

