import mongoose from "mongoose";
import { ID_SUFFIX, REF_GOLDENGATE, TYPE_MENU } from "../constants";

const generateId = (index: number) => new mongoose.Types.ObjectId(`${REF_GOLDENGATE}${TYPE_MENU}${ID_SUFFIX}${index.toString().padStart(6, "0")}`);

export const menus = [
	{
		_id: generateId(1),
		restaurantID: "goldengate",
		name: "Special Kitfo (ስፔሻል ክትፎ)",
		description: "Minced lean beef seasoned with mitmita and niter kibbeh, served with ayib and gomen.",
		category: "Main Course",
		price: 650,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/kitfo.png",
		hidden: false,
	},
	{
		_id: generateId(2),
		restaurantID: "goldengate",
		name: "Doro Wot (ዶሮ ወጥ)",
		description: "Spicy chicken stew slow-cooked with berbere, onions, and hard-boiled egg.",
		category: "Main Course",
		price: 700,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/doro_wot.png",
		hidden: false,
	},
	{
		_id: generateId(3),
		restaurantID: "goldengate",
		name: "Shiro Tegamino (ሽሮ ተጋቢኖ)",
		description: "Rich and flavorful chickpea stew served bubbling hot in a clay pot.",
		category: "Vegetarian",
		price: 350,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/shiro.png",
		hidden: false,
	},
	{
		_id: generateId(4),
		restaurantID: "goldengate",
		name: "Tibs (ጥብስ)",
		description: "Sizzling cubed meat (beef or lamb) sautéed with onions, rosemary, and jalapeños.",
		category: "Main Course",
		price: 550,
		taxPercent: 15,
		veg: "non-veg",
		image: "/uploads/ethiopian_food/tibs.png",
		hidden: false,
	},
	{
		_id: generateId(5),
		restaurantID: "goldengate",
		name: "Beyaynetu (በያይነቱ)",
		description: "Vegetarian fasting platter offering an assortment of colorful stews and vegetables.",
		category: "Vegetarian",
		price: 450,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/beyaynetu.png",
		hidden: false,
	},
	{
		_id: generateId(6),
		restaurantID: "goldengate",
		name: "Ethiopian Coffee (ቡና)",
		description: "Traditional freshly roasted and brewed Ethiopian coffee.",
		category: "Beverages",
		price: 50,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/coffee.png",
		hidden: false,
	},
	{
		_id: generateId(7),
		restaurantID: "goldengate",
		name: "Tej (ጠጅ)",
		description: "Traditional honey wine, sweet and potent.",
		category: "Beverages",
		price: 150,
		taxPercent: 15,
		veg: "veg",
		image: "/uploads/ethiopian_food/tej.png",
		hidden: false,
	},
];
